function destroyCutscene()
    destroyObject("car")
    destroyObject("drivethru")
    destroyObject("ground")
    destroyObject("clouds")
end
function Script()
    createObject("car","Car_Sprites/Car_Side.png")
    createObject("drivethru","mcdonalds/Drivethru.png")
    createObject("ground","mcdonalds/Ground.png")
    createObject("clouds","mcdonalds/Clouds.png")
    setLayer("car",4)
    setLayer("drivethru",3)
    setLayer("ground",2)
    setLayer("clouds",1)
    addShaderTo("car","RTX_SunsetLight.frag")
    addShaderTo("drivethru","RTX_SunsetLight.frag")
    addShaderTo("ground","RTX_SunsetLight.frag")
    startParallel("clouds",-4)
    playAnimationTwn("car","mcdonalds/car_pullup.twn")
    if waitForAnimation("car","mcdonalds/car_pullup.twn") then destroyCutscene() end
    createObject("drivethruWall","mcdonalds/Drivethru_Wall.png")
    createObject("officeCounter","mcdonalds/Office_Counter.png")
    createObject("operator","mcdonalds/Drivethru_Operator.png")
    createObject("officeBack","mcdonalds/Office_Back.png")
    setLayer("drivethruWall",4)
    setLayer("officeCounter",3)
    setLayer("operator",2)
    setLayer("officeBack",1)
    addShaderTo("drivethruWall","RTX_SunsetLight.frag")
    addShaderTo("operator","RTX_SunsetLight.frag")
    addShaderTo("officeCounter","RTX_SunsetLight.frag")
    addShaderTo("officeBack","RTX_LowLight.frag")
    if dialogue(("operator","greetings","mcdonalds/operator/greetings.wav")) then pickyPromptJSON("PickyPrompts/McDonalds_Order.json") end
end